# Generated by Django 5.2.4 on 2025-08-03 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_context_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='sub_comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_comment', to='posts.comment'),
        ),
    ]
