# Generated by Django 5.2.4 on 2025-08-03 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_comment_sub_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='sub_comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_comments', to='posts.comment'),
        ),
    ]
