# Generated by Django 5.2.4 on 2025-09-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_comment_likes_alter_post_savers_commentlike'),
        ('users', '0002_alter_profile_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookmarked_posts',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by', to='posts.post'),
        ),
    ]
