# Generated by Django 5.2.4 on 2025-09-19 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_bookmarked_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bookmarked_posts',
        ),
    ]
